### PR TITLE
Make switch work correct when props.{active, locked} has changed

### PR DESCRIPTION
**Pull request by lATAl**
This pull to make switch working correct when props.locked has changed.

```
<Switch locked={this.state.lockedSwitch} />
```

**Update**  I just added a commit to make active state will update when props.active has changed.

### CODE REVIEW

**Comment by nettofarah** [comment]
hey hey, @lATAl. Thank you so much for submitting this PR.
Things are looking good so far. But I'll need a bit more time to check it with more critical 👀
(probably over the weekend)

In the meantime, can you please just commit the source changes and maybe add some tests?

**Comment by nettofarah** [comment]
Btw, I'm surprised this just doesn't work automatically.
Correct me if I'm wrong, but shouldn't the switch component just be re-rendered when you change the `locked` prop?

What's your use case?
I think maybe adding a test case for this would help clarify this a lot.

**Comment by lATAl** [comment]
Hi @nettofarah.

When using switch with `locked` & `active` props is dynamic. This switch doesn't update when props change.

# `locked`

You add EventListener in `componentDidMount`. It is only called only one. After that, when a value of props has changed, `componentWillReceiveProps` will be called.
Look at the old code. After `locked` props has changed from the parent or server etc. Nothing happens.
But in new code, `componentWillReceiveProps` will be called, and EventListener will be added or remove.

# Same for `active`

Sorry for my bad English, but I hope you'd know what I mean.

**Comment by nettofarah** [comment]
hey, @lATAl. No worries, your english is great!
I think I get what's going on now.

I'll check your PR and get back to you soon.

Thanks again!

**Comment by nettofarah** [comment]
Hey, @lATAl. Just merged your PR to master.
I'll write some tests and create a new release when I have a chance

**Comment by nettofarah** [comment]
Just published v0.3.4 on npm

**Comment by lATAl** [comment]
👍

**Pull request merged**
